# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp for homework of Chapter 9 
#' @param a the parameter of the given density
#' @param b the parameter of the given density
#' @param n the parameter of the given density
#' @param N the number of samples
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' GC<- GibbsC(1,1,25,10000)
#' plot(GC[,1],main= paste("a=",a,",b=",b,",n=",n,",Condition function:Binomial"))
#' plot(GC[,2],main= paste("a=",a,",b=",b,",n=",n,",Condition function:Beta"))
#' }
#' @export
GibbsC <- function(a, b, n, N) {
    .Call('_StatComp21040_GibbsC', PACKAGE = 'StatComp21040', a, b, n, N)
}

